---
   - name: Import InfluxDB GPG signing key
     apt_key: url=https://repos.influxdata.com/influxdb.key state=present

   - name: Add InfluxDB repository
     apt_repository: repo='deb https://repos.influxdata.com/ubuntu xenial stable' state=present

   - name: Install InfluxDB
     apt: name=influxdb state=present

   - name: Restart InfluxDB
     service: name=influxd state=restarted

   - name: Install python-influxdb
     apt: name=python-influxdb state=present

   - name: Create test database
     influxdb_database: 
         hostname: "127.0.0.1"
         database_name: "test"
         state: present