---
   - name: Updating apt cache
     apt:
       update_cache: yes

   - name: Install Nodejs
     apt: 
       name: nodejs
       state: present

   - name: Install NPM
     apt: name=npm state=present

   - name: Clone dockerwatch-influx
     git:
       repo: "https://github.com/shanel262/dockerwatch-influx"
       dest: /home/dockerwatch-influx

   - name: NPM install node_modules
     npm:
       path: /home/dockerwatch-influx

   - name: Upload config.yml
     template:
       src: "config.yml.j2"
       dest: "/home/dockerwatch-influx/config.yml"

   - name: Install Forever
     npm: name=forever global=yes state=present

   - name: Symlink from /usr/bin/nodejs to /usr/bin/node
     shell: ln -s /usr/bin/nodejs /usr/bin/node

   - name: Start Nodejs service
     shell: nohup forever start server.js
     args:
       chdir: /home/dockerwatch-influx
